# Generated by Django 3.1 on 2020-08-15 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=140)),
                ('initial_bid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_bid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image_url', models.CharField(max_length=140)),
                ('category', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('date_posted', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bidlistings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
