# Generated by Django 3.1 on 2020-08-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200816_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='is_greater',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=1400),
        ),
    ]
