# Generated by Django 3.1 on 2020-08-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200819_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_img',
            field=models.CharField(blank=True, max_length=1400, null=True),
        ),
    ]
